# Reference this view as products
label: Produits

dimensions:
  category:
    label: Catégorie

  name:
    label: Nom

  brand:
    label: Marque

  retail_price:
    label: Prix de détail

  department:
    label: Département

  sku:
    label: SKU

  id:
    label: Identifiant

  distribution_center_id:
    label: Centre de distribution

measures:
  count:
    label: Compte
    aggregate_type: count
