joins:
  users: {}

views:
  orders:
    dimensions:
      status:
        label: Status in Topic

  users:
    dimensions:
      full_name:
        sql: concat(concat(${first_name}, ' '), ${last_name})

    measures:
      topic_only_count:
        sql: ${count} + 1000000
