joins:
  orders:
    order_items: {}

views:
  users_ext:
    extends: [ users ]

    dimensions:
      topic_only_age:
        sql: age

      age:
        label: age lbeled in topics

  orders:
    dimensions:
      seller_id:
        label: Topic Seller Id

relationships:
  - join_from_view: orders
    join_to_view: users_ext
    join_type: always_left
    on_sql: ${orders.user_id} = ${users_ext.id}
    relationship_type: assumed_many_to_one
