base_view: extends_orders

# this is the orders topic
joins:
  users: {}

views:
  extends_orders:
    extends: [ orders ]

relationships:
  - join_from_view: extends_orders
    join_to_view: users
    join_type: always_left
    on_sql: ${extends_orders.user_id} = ${users.id}
    relationship_type: assumed_many_to_one
